Import('*')

lib = env.Clone()

lib['CPPDEFINES'] = []
if DEBUG:
	lib['CPPDEFINES'] += ['DEBUG']

Default(lib.StaticLibrary(
	'static-grf',
	['grf.c', 'grfcrypt.c', 'grfsupport.c', 'rgz.c', 'sprite.c'],
	CPPPATH=['$CPPPATH', '.', 'zlib']))
